name: "Build and Deploy Frontend to GKE"

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  GKE_CLUSTER: "${{ secrets.GKE_CLUSTER }}"
  GKE_ZONE: "${{ secrets.GKE_ZONE }}"
  GKE_NAMESPACE: "${{ secrets.GKE_NAMESPACE }}"
  GAR_REGION: "${{ secrets.GAR_REGION }}"
  GAR_NAME: "${{ secrets.GAR_NAME }}"
  GCR_SERVICE: "${{ secrets.GCR_SERVICE }}"
  IMAGE_TAG: "${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ secrets.GAR_NAME }}/${{ secrets.GCR_SERVICE }}:latest"

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Authenticate to GCP"
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDS }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Install gke-gcloud-auth-plugin"
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: "Docker Auth To GAR"
        run: |
          gcloud auth configure-docker "${{ env.GAR_REGION }}-docker.pkg.dev"

      - name: "Build and Push Frontend Image"
        run: |
          docker build --tag "${{ env.IMAGE_TAG }}" .
          docker push "${{ env.IMAGE_TAG }}"

      - name: "Get GKE Credentials"
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }} --project ${{ env.PROJECT_ID }}

      - name: "Deploy Frontend to GKE"
        run: |
          kubectl apply -f kubernetes/frontend-deployment.yaml -n ${{ env.GKE_NAMESPACE }}
          kubectl apply -f kubernetes/frontend-service.yaml -n ${{ env.GKE_NAMESPACE }}

      - name: "Restart Frontend Deployment"
        run: |
          kubectl rollout restart deployment frontend -n ${{ env.GKE_NAMESPACE }}

      - name: "Show Service Output"
        run: |
          kubectl get svc frontend -n ${{ env.GKE_NAMESPACE }}
